FROM python:3.13.3-bullseye

RUN python -m venv /opt/venv/
ENV PATH=/opt/venv/bin:$PATH

WORKDIR /app

COPY ./requirements.txt /tmp/requirements.txt

COPY ./src /app/

RUN pip install pip --upgrade
RUN pip install -r /tmp/requirements.txt

# uvicorn main:app --host 0.0.0.0 --port 8002 --reload
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002", "--reload"]