FROM python:3.13.3-bullseye

RUN python -m venv /opt/venv/
ENV PATH=/opt/venv/bin:$PATH

WORKDIR /app

COPY ./requirements.txt /tmp/requirements.txt

COPY ./src /app/

RUN pip install pip --upgrade
RUN pip install -r /tmp/requirements.txt

# 8888
CMD ["python", "manage.py", "runserver", "0.0.0.0:8888"]